// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Utils from "../src/utils/Utils.res.js";
import * as Buntest from "bun:test";

Buntest.describe("Utils", (function () {
        Buntest.test("addition works", (function () {
                Buntest.expect(Utils.add(2, 2)).toBe(4);
              }));
      }));

export {
  
}
/*  Not a pure module */
