// Generated by ReScript, PLEASE EDIT WITH CARE

import * as PervasivesU from "rescript/lib/es6/pervasivesU.js";

function _parseSchemaType(schemaType) {
  switch (schemaType) {
    case "int" :
        return "INTEGER";
    case "string" :
        return "TEXT";
    default:
      return PervasivesU.failwith("Unsupported schema type: " + schemaType);
  }
}

function create(tableName, schema) {
  console.log("Creating table: " + tableName);
  var start = "CREATE TABLE " + tableName + " (";
  var columns = schema.map(function (column) {
          var val = _parseSchemaType(column._type);
          var primaryKey = column.primaryKey ? " PRIMARY KEY" : "";
          var optionnal = column.optionnal ? " NOT NULL" : "";
          var $$default = column.default !== "" ? " DEFAULT " + column.default : "";
          return column.name + " " + val + primaryKey + optionnal + $$default;
        }).join(", ");
  return start + columns + ");";
}

export {
  _parseSchemaType ,
  create ,
}
/* No side effect */
