// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Builder from "./Builder.res.js";

var userSchema = Builder.create("users", [
      {
        name: "id",
        _type: "int",
        primaryKey: true,
        optionnal: false,
        default: "''"
      },
      {
        name: "name",
        _type: "string",
        primaryKey: false,
        optionnal: false,
        default: "''"
      },
      {
        name: "email",
        _type: "string",
        primaryKey: false,
        optionnal: false,
        default: "''"
      }
    ]);

console.log(userSchema);

export {
  userSchema ,
}
/* userSchema Not a pure module */
