// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import * as Belt_Option from "rescript/lib/es6/belt_Option.js";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as Caml_js_exceptions from "rescript/lib/es6/caml_js_exceptions.js";

function add(a, b) {
  return a + b | 0;
}

function handlePgError(pgError) {
  var jsExn = Caml_js_exceptions.as_js_exn(pgError);
  var errorMessage = jsExn !== undefined ? Belt_Option.getWithDefault(Caml_option.valFromOption(jsExn).message, "Erreur inconnue") : "Erreur inconnue";
  console.error("Erreur lors de l'exécution de la requête : " + errorMessage);
}

function formatRows(pgResult) {
  return Belt_Array.map(pgResult.rows, (function (row) {
                  return JSON.stringify(row);
                })).join(", ");
}

var Utils = {
  add: add,
  handlePgError: handlePgError,
  formatRows: formatRows
};

export {
  Utils ,
}
/* No side effect */
