// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Db = require("../core/Db.res.js");
var Belt_Array = require("rescript/lib/js/belt_Array.js");
var Belt_Option = require("rescript/lib/js/belt_Option.js");
var Caml_option = require("rescript/lib/js/caml_option.js");
var Caml_js_exceptions = require("rescript/lib/js/caml_js_exceptions.js");

function add(a, b) {
  return a + b | 0;
}

function handlePgError(pgError) {
  var jsExn = Caml_js_exceptions.as_js_exn(pgError);
  var errorMessage = jsExn !== undefined ? Belt_Option.getWithDefault(Caml_option.valFromOption(jsExn).message, "Erreur inconnue") : "Erreur inconnue";
  console.error("Erreur lors de l'exécution de la requête : " + errorMessage);
}

function formatRows(pgResult) {
  return Belt_Array.map(pgResult.rows, (function (row) {
                  return JSON.stringify(row);
                })).join(", ");
}

async function connectToDb(config) {
  var client = await Db.Db.connectToDb(config);
  console.log("Connexion réussie à la base de données");
  return client;
}

var Utils = {
  add: add,
  handlePgError: handlePgError,
  formatRows: formatRows,
  connectToDb: connectToDb
};

exports.Utils = Utils;
/* Db Not a pure module */
