// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var PgClient = require("PgClient");
var Core__Promise = require("@rescript/core/src/Core__Promise.res.js");

function connectToDb(config) {
  var client = PgClient.make(config.user, config.password, config.host, config.database, config.port);
  return Core__Promise.$$catch(PgClient.connect(client).then(function () {
                  console.log("Connected to the database");
                  return Promise.resolve(client);
                }), (function (e) {
                console.error("Failed to connect to the database", e);
                return Promise.reject(e);
              }));
}

var Db = {
  connectToDb: connectToDb
};

exports.Db = Db;
/* PgClient Not a pure module */
