// Generated by ReScript, PLEASE EDIT WITH CARE

import * as PgBind from "../bindings/PgBind.res.js";
import * as Core__Promise from "@rescript/core/src/Core__Promise.res.js";

function connectToDb() {
  var client = PgBind.PgClient.make("admin", "adminpwd", "localhost", "db", 5432, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined);
  return Core__Promise.$$catch(client.connect().then(function () {
                  console.log("Connected to the database");
                  return client.end();
                }), (function (e) {
                console.error("Failed to connect to the database", e);
                return Promise.resolve();
              }));
}

export {
  connectToDb ,
}
/* PgBind Not a pure module */
