// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Config from "../config/config.res.js";
import * as PgBind from "../bindings/PgBind.res.js";
import * as Core__Promise from "@rescript/core/src/Core__Promise.res.js";

function connectToDb() {
  var client = PgBind.PgClient.make(Config.Config.defaultConfig.user, Config.Config.defaultConfig.password, Config.Config.defaultConfig.host, Config.Config.defaultConfig.database, Config.Config.defaultConfig.port, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined);
  return Core__Promise.$$catch(client.connect().then(function () {
                  console.log("Connected to the database");
                  return Promise.resolve(client);
                }), (function (e) {
                console.error("Failed to connect to the database", e);
                return Promise.reject(e);
              }));
}

export {
  connectToDb ,
}
/* PgBind Not a pure module */
